### ISSUE TITLE
some problems about dataset and models.py

### ISSUE THREAD

**Issue by aaronhd** [swchui/Grasping-state-assessment#2]
Hi swchui!

1. It seems a bad file of test_tactile_5.npy, which should be 170MB approximately. Can you check and re-upload the file if the file is indeed bad.

2.  There are two python modules missing: **LSTHM** and **mypath**  in models.py. Can you provide more details about them?
 
Thank you!

**Comment by cui-shaowei** [comment]
Hi aaronhd!

Thanks for your attention.
we have uploaded the **LSTHM** and **mypath** file, sorry for this issue.

Sincerely,
Shaowei
